import { useEffect, useState } from "react";
import { apiClient, type ApiDocument, type ApiFinding, type ApiField, type CaseSummary, type PlatformActivity, type PlatformArchitecture, type PlatformStatus, type UseCaseDefinition } from "./api-client.js";
import { ClientMode } from "./components/ClientMode.js";
import { InclusionMode } from "./components/InclusionMode.js";
import { ConversationColumn } from "./components/ConversationColumn.js";
import { DocumentsColumn } from "./components/DocumentsColumn.js";
import { ErrorBanner } from "./components/ErrorBanner.js";
import { EvidencePanel } from "./components/EvidencePanel.js";
import { OperationsMode } from "./components/OperationsMode.js";
import { ReviewColumn } from "./components/ReviewColumn.js";
import { SecurityMode } from "./components/SecurityMode.js";
import { StatusBadge } from "./components/StatusBadge.js";
import { PlatformHome } from "./components/PlatformHome.js";
import { UiErrorBoundary } from "./components/UiErrorBoundary.js";
import "./styles.css";
import "./expansion.css";
type Mode = "home" | "client" | "inclusion" | "documents" | "operations" | "security";
const fallbackCase: CaseSummary = { id: "case-0001", status: "nuevo", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() };
const modeMeta: Record<Mode, { eyebrow: string; title: string; description: string; action: string }> = {
  home: { eyebrow: "CENTRO DE TRABAJO", title: "Inteligencia bancaria cerca del dato", description: "Selecciona un objetivo para orientar, revisar, asistir la operación o investigar señales con QVAC local.", action: "Empieza eligiendo un objetivo de trabajo." },
  client: { eyebrow: "MODO CLIENTE", title: "Encuentra orientación para tu próximo paso", description: "Explora opciones sencillas y pregunta al asistente local sin compartir información personal.", action: "Empieza consultando un producto o una guía." },
  inclusion: { eyebrow: "MODO INCLUSIÓN", title: "Aprende y decide con información clara", description: "Contenido breve, bilingüe y pensado para conectividad limitada y distintos niveles de experiencia.", action: "Empieza por una guía de educación financiera." },
  documents: { eyebrow: "MODO DOCUMENTOS", title: "Revisa un expediente con evidencia", description: "Carga documentos sintéticos, ejecuta el análisis y verifica cada resultado hasta su página de origen.", action: "Empieza seleccionando un expediente o cargando un PDF." },
  operations: { eyebrow: "MODO OPERACIÓN", title: "Apoya tu trabajo con reglas locales", description: "Consulta procedimientos y revisa solicitudes sin que el asistente ejecute cambios por ti.", action: "Empieza haciendo una pregunta de procedimiento." },
  security: { eyebrow: "MODO SEGURIDAD", title: "Observa señales para revisión humana", description: "Consulta patrones documentales y transaccionales sintéticos con una explicación clara.", action: "Empieza revisando las alertas pendientes." },
};
export function App() {
  const [mode, setMode] = useState<Mode>("home"); const [language, setLanguage] = useState<"es" | "en">("es"); const [highContrast, setHighContrast] = useState(false); const [largeText, setLargeText] = useState(false); const [online, setOnline] = useState(() => navigator.onLine);
  const [cases, setCases] = useState<CaseSummary[]>([]); const [selected, setSelected] = useState<CaseSummary>(fallbackCase); const [documents, setDocuments] = useState<ApiDocument[]>([]); const [fields, setFields] = useState<ApiField[]>([]); const [findings, setFindings] = useState<ApiFinding[]>([]); const [messages, setMessages] = useState<string[]>([]); const [ready, setReady] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [finding, setFinding] = useState<ApiFinding | null>(null); const [useCases, setUseCases] = useState<UseCaseDefinition[]>([]); const [architecture, setArchitecture] = useState<PlatformArchitecture | null>(null); const [platformStatus, setPlatformStatus] = useState<PlatformStatus | null>(null); const [activity, setActivity] = useState<PlatformActivity[]>([]);
  const refreshCase = async (caseId: string) => { const [docs, analysis] = await Promise.all([apiClient.documents(caseId), apiClient.analysis(caseId)]); setDocuments(docs); setFields(analysis.fields); setFindings(analysis.findings); };
  const load = async () => { try { const [available, health, definitions, architectureData, status, recentActivity] = await Promise.all([apiClient.cases(), apiClient.health(), apiClient.platformUseCases(), apiClient.platformArchitecture(), apiClient.platformStatus(), apiClient.platformActivity()]); const next = available[0] ?? fallbackCase; setCases(available); setSelected(next); setReady(health.ready); setUseCases(definitions); setArchitecture(architectureData); setPlatformStatus(status); setActivity(recentActivity); if (available[0]) await refreshCase(next.id); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo conectar con la API local"); } };
  useEffect(() => { void load(); const on = () => setOnline(true); const off = () => setOnline(false); window.addEventListener("online", on); window.addEventListener("offline", off); return () => { window.removeEventListener("online", on); window.removeEventListener("offline", off); }; }, []);
  const analyze = async () => { setBusy(true); setError(null); try { const result = await apiClient.agentTurn(selected.id); setMessages(current => [...current, result.action.text ?? result.action.summary ?? "El agente terminó la revisión."]); const available = await apiClient.cases(); const current = available.find(item => item.id === selected.id); if (current) setSelected(current); await refreshCase(selected.id); } catch (caught) { setError(caught instanceof Error ? caught.message : "QVAC local no está listo"); } finally { setBusy(false); } };
  const upload = async (file: File) => { setBusy(true); setError(null); try { const uploaded = await apiClient.upload(selected.id, file); await refreshCase(selected.id); let attempts = 0; const poll = async () => { if (attempts++ >= 120) return; const response = await fetch(`/api/cases/${selected.id}/documents/${uploaded.id}/processing`); const processing = await response.json() as { processingStatus: string; error?: string }; await refreshCase(selected.id); if (["completed", "failed", "requires_review"].includes(processing.processingStatus)) { if (processing.error) setError(processing.error); return; } window.setTimeout(() => void poll(), 500); }; void poll(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Documento rechazado"); } finally { setBusy(false); } };
  const clearDocuments = async () => { if (!documents.length || !window.confirm("¿Eliminar los documentos procesados y sus evidencias locales?")) return; setBusy(true); setError(null); try { for (const document of documents) { const response = await fetch(`/api/cases/${selected.id}/documents/${document.id}`, { method: "DELETE" }); if (!response.ok) throw new Error("No se pudo eliminar un documento"); } await refreshCase(selected.id); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudieron limpiar los documentos"); } finally { setBusy(false); } };
  const createCase = async () => { setBusy(true); setError(null); try { const created = await apiClient.createCase("Mi expediente"); const available = await apiClient.cases(); setCases(available); setSelected(created); await refreshCase(created.id); setMessages(["Expediente nuevo listo. Ahora carga un PDF sintético y ejecuta el análisis."]); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo crear el expediente"); } finally { setBusy(false); } };
  const report = async () => { setBusy(true); setError(null); try { const result = await apiClient.report(selected.id); const url = URL.createObjectURL(new Blob([result.html], { type: "text/html" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${selected.id}-reporte.html`; anchor.click(); URL.revokeObjectURL(url); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo generar el reporte"); } finally { setBusy(false); } };
  const openDocuments = async () => { setError(null); try { const ownCases = cases.filter(item => item.id.startsWith("case-user-")); if (ownCases.length) { const next = ownCases[ownCases.length - 1]; setSelected(next); await refreshCase(next.id); await apiClient.startWorkspace("document_review", "reviewer", next.id); } else { const created = await apiClient.createCase("Mi expediente"); const available = await apiClient.cases(); setCases(available); setSelected(created); await refreshCase(created.id); await apiClient.startWorkspace("document_review", "reviewer", created.id); } setMode("documents"); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo abrir Documentos"); } };
  useEffect(() => { if (mode === "documents" && !selected.id.startsWith("case-user-")) void openDocuments(); }, [mode]);
  const selectUseCase = async (item: UseCaseDefinition) => { if (item.entryMode === "documents") { await openDocuments(); return; } const role = item.entryMode === "security" ? "security_analyst" : item.entryMode === "operations" ? "bank_operator" : "client"; try { await apiClient.startWorkspace(item.id, role); setActivity(await apiClient.platformActivity()); setMode(item.entryMode); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo iniciar el espacio de trabajo"); } };
  const documentScreen = <><section className="case-toolbar"><div><span className="eyebrow">MIS DOCUMENTOS</span><p>Carga tus archivos y procesa todo localmente. No necesitas gestionar expedientes.</p></div><div className="local-pill">● QVAC local</div></section><section className="workspace"><DocumentsColumn documents={documents} status={selected.status} onUpload={file => void upload(file)} onClear={() => void clearDocuments()} busy={busy} /><ConversationColumn messages={messages} onAnalyze={() => void analyze()} busy={busy} ready={ready} /><ReviewColumn selected={selected} fields={fields} findings={findings} onFinding={setFinding} onReport={() => void report()} busy={busy} /></section><EvidencePanel finding={finding} documents={documents} onClose={() => setFinding(null)} /></>;
  const screen = mode === "home" && architecture ? <PlatformHome useCases={useCases} architecture={architecture} status={platformStatus} activity={activity} onSelect={item => void selectUseCase(item)} /> : mode === "client" ? <ClientMode language={language} onLanguageChange={setLanguage} /> : mode === "inclusion" ? <InclusionMode language={language} onLanguageChange={setLanguage} /> : mode === "operations" ? <UiErrorBoundary name="Operación"><OperationsMode /></UiErrorBoundary> : mode === "security" ? <SecurityMode /> : documentScreen;
  const meta = modeMeta[mode];
  return <main className={`app-shell ${highContrast ? "high-contrast" : ""} ${largeText ? "large-text" : ""}`}><header className="topbar"><div className="brand"><span className="brand-mark">QB</span><div><strong>Centro Bancario Local</strong><span>Tu espacio privado de orientación y revisión</span></div></div><div className="topbar-meta"><span className="synthetic-tag">DEMO CON DATOS SINTÉTICOS</span><span className="model-status"><i className={ready ? "ready" : ""} />{ready ? "QVAC local listo" : "QVAC local pendiente"}</span></div></header><div className={`offline-banner ${online ? "" : "offline"}`} role="status"><span className="status-dot" />{online ? "Modo local activo · puedes trabajar con los datos disponibles" : "Estás sin internet · el contenido local sigue disponible"}</div><nav className="mode-nav" aria-label="Elige un área de trabajo">{([["client", "Cliente"], ["inclusion", "Inclusión"], ["documents", "Documentos"], ["operations", "Operación"], ["security", "Seguridad"]] as const).map(([key, label], index) => <button className="mode-button" aria-pressed={mode === key} key={key} onClick={() => setMode(key)}><span className="mode-number">0{index + 1}</span>{label}</button>)}</nav><div className="accessibility-bar"><span>Personaliza tu vista</span><button onClick={() => setHighContrast(value => !value)} aria-pressed={highContrast}>◐ Contraste</button><button onClick={() => setLargeText(value => !value)} aria-pressed={largeText}>A Texto grande</button></div><section className="mode-intro"><div><span className="eyebrow">{meta.eyebrow}</span><h1>{meta.title}</h1><p>{meta.description}</p></div><div className="next-step"><span>PRIMER PASO</span><strong>{meta.action}</strong></div></section>{error && <ErrorBanner message={error} onRetry={() => void load()} />}{screen}<footer className="footer"><span>Privacidad local <strong>· QVAC en tu dispositivo</strong></span><span>Solo datos sintéticos · La decisión final siempre es humana</span></footer></main>;
}
