import { useEffect, useState } from "react";
import { apiClient, type ApiDocument, type ApiFinding, type ApiField, type CaseSummary } from "./api-client.js";
import { ClientMode } from "./components/ClientMode.js";
import { ConversationColumn } from "./components/ConversationColumn.js";
import { DocumentsColumn } from "./components/DocumentsColumn.js";
import { ErrorBanner } from "./components/ErrorBanner.js";
import { EvidencePanel } from "./components/EvidencePanel.js";
import { OperationsMode } from "./components/OperationsMode.js";
import { ReviewColumn } from "./components/ReviewColumn.js";
import { SecurityMode } from "./components/SecurityMode.js";
import { StatusBadge } from "./components/StatusBadge.js";
import "./styles.css";
import "./expansion.css";
type Mode = "client" | "inclusion" | "documents" | "operations" | "security";
const fallbackCase: CaseSummary = { id: "case-0001", status: "nuevo", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() };
export function App() {
  const [mode, setMode] = useState<Mode>("client"); const [language, setLanguage] = useState<"es" | "en">("es"); const [highContrast, setHighContrast] = useState(false); const [largeText, setLargeText] = useState(false); const [online, setOnline] = useState(() => navigator.onLine);
  const [cases, setCases] = useState<CaseSummary[]>([]); const [selected, setSelected] = useState<CaseSummary>(fallbackCase); const [documents, setDocuments] = useState<ApiDocument[]>([]); const [fields, setFields] = useState<ApiField[]>([]); const [findings, setFindings] = useState<ApiFinding[]>([]); const [messages, setMessages] = useState<string[]>([]); const [ready, setReady] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [finding, setFinding] = useState<ApiFinding | null>(null);
  const refreshCase = async (caseId: string) => { const [docs, analysis] = await Promise.all([apiClient.documents(caseId), apiClient.analysis(caseId)]); setDocuments(docs); setFields(analysis.fields); setFindings(analysis.findings); };
  const load = async () => { try { const [available, health] = await Promise.all([apiClient.cases(), apiClient.health()]); const next = available[0] ?? fallbackCase; setCases(available); setSelected(next); setReady(health.ready); if (available[0]) await refreshCase(next.id); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo conectar con la API local"); } };
  useEffect(() => { void load(); const on = () => setOnline(true); const off = () => setOnline(false); window.addEventListener("online", on); window.addEventListener("offline", off); return () => { window.removeEventListener("online", on); window.removeEventListener("offline", off); }; }, []);
  const analyze = async () => { setBusy(true); setError(null); try { const result = await apiClient.agentTurn(selected.id); setMessages(current => [...current, result.action.text ?? result.action.summary ?? "El agente terminó la revisión."]); const available = await apiClient.cases(); const current = available.find(item => item.id === selected.id); if (current) setSelected(current); await refreshCase(selected.id); } catch (caught) { setError(caught instanceof Error ? caught.message : "QVAC local no está listo"); } finally { setBusy(false); } };
  const upload = async (file: File) => { setBusy(true); setError(null); try { await apiClient.upload(selected.id, file); await refreshCase(selected.id); } catch (caught) { setError(caught instanceof Error ? caught.message : "Documento rechazado"); } finally { setBusy(false); } };
  const report = async () => { setBusy(true); setError(null); try { const result = await apiClient.report(selected.id); const url = URL.createObjectURL(new Blob([result.html], { type: "text/html" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${selected.id}-reporte.html`; anchor.click(); URL.revokeObjectURL(url); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo generar el reporte"); } finally { setBusy(false); } };
  const screen = mode === "client" || mode === "inclusion" ? <ClientMode language={language} onLanguageChange={setLanguage} /> : mode === "operations" ? <OperationsMode /> : mode === "security" ? <SecurityMode /> : <><section className="hero"><div><span className="eyebrow">SUCURSAL / DOCUMENTOS</span><h1>Un expediente claro<br /><em>empieza con evidencia.</em></h1></div><div className="case-selector"><label>Expediente activo</label><select aria-label="Expediente activo" value={selected.id} onChange={event => { const next = cases.find(item => item.id === event.target.value); if (next) { setSelected(next); void refreshCase(next.id); } }}><option value={selected.id}>{selected.id}</option>{cases.filter(item => item.id !== selected.id).map(item => <option key={item.id} value={item.id}>{item.id}</option>)}</select><StatusBadge status={selected.status} /></div></section><section className="workspace"><DocumentsColumn documents={documents} status={selected.status} onUpload={file => void upload(file)} busy={busy} /><ConversationColumn messages={messages} onAnalyze={() => void analyze()} busy={busy} ready={ready} /><ReviewColumn selected={selected} fields={fields} findings={findings} onFinding={setFinding} onReport={() => void report()} busy={busy} /></section><EvidencePanel finding={finding} documents={documents} onClose={() => setFinding(null)} /></>;
  return <main className={`app-shell ${highContrast ? "high-contrast" : ""} ${largeText ? "large-text" : ""}`}><header className="topbar"><div className="brand"><span className="brand-mark">EL</span><div><strong>Centro Bancario Local</strong><span>Inteligencia privada para la banca</span></div></div><div className="topbar-meta"><span className="synthetic-tag">DATOS SINTÉTICOS — DEMO</span><span className="model-status"><i className={ready ? "ready" : ""} />{ready ? "QVAC local listo" : "QVAC local pendiente"}</span></div></header><div className={`offline-banner ${online ? "" : "offline"}`} role="status">{online ? "Conectividad disponible · servicios locales" : "Sin internet · modo local disponible"}</div><nav className="mode-nav" aria-label="Modos del centro bancario">{([["client", "Cliente"], ["inclusion", "Inclusión"], ["documents", "Documentos"], ["operations", "Operación"], ["security", "Seguridad"]] as const).map(([key, label]) => <button className="mode-button" aria-pressed={mode === key} key={key} onClick={() => setMode(key)}>{label}</button>)}</nav><div className="accessibility-bar"><span>Accesibilidad:</span><button onClick={() => setHighContrast(value => !value)} aria-pressed={highContrast}>Alto contraste</button><button onClick={() => setLargeText(value => !value)} aria-pressed={largeText}>Texto grande</button></div>{error && <ErrorBanner message={error} onRetry={() => void load()} />}{screen}<footer className="footer"><span>Inferencia: <strong>QVAC local</strong> · LLAMA_3_2_1B_INST_Q4_0</span><span>Solo datos sintéticos · Sin nube · Revisión humana</span></footer></main>;
}
