import { useEffect, useState } from "react";
import { apiClient, type AssistantAnswer, type Guide, type Product } from "../api-client.js";

export function ClientMode({ language, onLanguageChange }: { language: "es" | "en"; onLanguageChange: (value: "es" | "en") => void }) {
  const [products, setProducts] = useState<Product[]>([]); const [guides, setGuides] = useState<Guide[]>([]); const [query, setQuery] = useState(""); const [answer, setAnswer] = useState<AssistantAnswer | null>(null); const [selected, setSelected] = useState<Product | null>(null); const [message, setMessage] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { void Promise.all([apiClient.products(language), apiClient.guides(language)]).then(([p, g]) => { setProducts(p); setGuides(g); }).catch(() => setNotice("No se pudo cargar el catálogo local.")); }, [language]);
  const ask = async () => { if (!query.trim()) return; setBusy(true); try { setAnswer(await apiClient.clientAssistant(language, query)); } catch { setNotice("El asistente local no pudo responder."); } finally { setBusy(false); } };
  const save = async () => { if (!selected) return; setBusy(true); try { await apiClient.orientation(selected.id, language, message || "Solicito orientación sobre este producto."); setNotice("Solicitud local guardada para revisión humana en Sucursal."); setSelected(null); setMessage(""); } catch { setNotice("No se pudo guardar el borrador local."); } finally { setBusy(false); } };
  return <section className="mode-content"><div className="content-toolbar"><div><strong>Contenido disponible</strong><span>Todo lo que ves aquí está guardado localmente.</span></div><label>Idioma <select aria-label="Idioma del contenido" value={language} onChange={e => onLanguageChange(e.target.value as "es" | "en")}><option value="es">Español claro</option><option value="en">English</option></select></label></div><div className="client-grid"><article className="mode-card"><h3>{language === "es" ? "Productos" : "Products"}</h3>{products.map(p => <div className="catalog-item" key={p.id}><strong>{p.name}</strong><p>{p.description}</p><small>{p.audience} · Requisitos: {p.requirements}</small><button onClick={() => setSelected(p)}>Guardar interés local</button></div>)}</article><article className="mode-card"><h3>{language === "es" ? "Educación financiera" : "Financial education"}</h3>{guides.map(g => <div className="catalog-item" key={g.id}><strong>{g.title}</strong><p>{g.content}</p></div>)}</article></div><article className="mode-card assistant-card"><h3>Asistente local QVAC</h3><p className="helper-text">¿Tienes una duda? Escribe una pregunta y te responderé usando solo el contenido local.</p><div className="inline-form"><input aria-label="Pregunta para el asistente" value={query} onChange={e => setQuery(e.target.value)} placeholder="Ej.: ¿Cómo puedo ahorrar?" /><button onClick={() => void ask()} disabled={busy}>Consultar</button></div>{answer && <div className="answer-card"><p>{answer.answer}</p><small>Fuente: {answer.sources.map(s => s.title).join(", ") || "catálogo local"} · {answer.provider}</small></div>}</article>{selected && <div className="modal-card"><h3>Solicitud de orientación</h3><p>{selected.name}. Es un borrador sintético, no una solicitud bancaria.</p><textarea aria-label="Mensaje de orientación" value={message} onChange={e => setMessage(e.target.value)} placeholder="¿Qué quieres consultar?" /><button onClick={() => void save()} disabled={busy}>Guardar para revisión humana</button><button className="secondary-button" onClick={() => setSelected(null)}>Cancelar</button></div>}{notice && <p className="notice" role="status">{notice}</p>}</section>;
}
