import { useEffect, useState } from "react";
import { apiClient, type Guide } from "../api-client.js";
import { AssistantComposer } from "./AssistantComposer.js";

export function InclusionMode({ language, onLanguageChange }: { language: "es" | "en"; onLanguageChange: (value: "es" | "en") => void }) {
  const [guides, setGuides] = useState<Guide[]>([]); const [query, setQuery] = useState(""); const [notice, setNotice] = useState(""); const [answer, setAnswer] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { void apiClient.guides(language).then(setGuides).catch(() => setNotice("No se pudieron cargar las guías locales.")); }, [language]);
  const ask = async () => { if (!query.trim()) return; setBusy(true); setNotice(""); try { const result = await apiClient.clientAssistant(language, query); setAnswer(result.answer); } catch { setNotice("El asistente local no pudo responder. Intenta de nuevo."); } finally { setBusy(false); } };
  return <section className="mode-content"><div className="content-toolbar"><div><strong>{language === "es" ? "Información para todas las personas" : "Information for everyone"}</strong><span>{language === "es" ? "Contenido breve, claro y disponible aun con conectividad limitada." : "Short, clear content available even with limited connectivity."}</span></div><label>Idioma <select aria-label="Idioma de inclusión" value={language} onChange={e => onLanguageChange(e.target.value as "es" | "en")}><option value="es">Español claro</option><option value="en">English</option></select></label></div><div className="inclusion-tiles"><article><span className="tile-icon">Aa</span><strong>Lenguaje claro</strong><p>Explicaciones sin tecnicismos para tomar decisiones con confianza.</p></article><article><span className="tile-icon">⌁</span><strong>Modo local</strong><p>Las guías permanecen disponibles cuando la conexión es intermitente.</p></article><article><span className="tile-icon">✓</span><strong>Seguridad</strong><p>Nunca compartas claves, contraseñas ni códigos de un solo uso.</p></article></div><article className="mode-card"><div className="card-heading"><div><span className="card-kicker">APRENDE A TU RITMO</span><h3>{language === "es" ? "Guías de educación financiera" : "Financial education guides"}</h3></div><span className="card-count">{guides.length} guías locales</span></div><div className="guide-grid">{guides.map(guide => <div className="guide-card" key={guide.id}><strong>{guide.title}</strong><p>{guide.content}</p><small>Fuente local · {guide.version}</small></div>)}</div></article><AssistantComposer eyebrow="APOYO PARA ENTENDER" title={language === "es" ? "Pregunta con tus propias palabras" : "Ask in your own words"} description="No necesitas conocer términos bancarios. Te explico lo esencial paso a paso, usando contenido local." inputLabel="Pregunta de inclusión financiera" placeholder={language === "es" ? "Ej.: ¿Cómo cuido mi cuenta?" : "Example: How do I protect my account?"} submitLabel={language === "es" ? "Explicarme" : "Explain"} suggestions={language === "es" ? ["¿Cómo cuido mi cuenta?", "¿Qué es ahorrar?", "¿Qué nunca debo compartir?"] : ["How do I protect my account?", "What is saving?", "What should I never share?"]} query={query} busy={busy} onQueryChange={setQuery} onAsk={() => void ask()} answer={answer && <p>{answer}</p>} answerMeta="Respuesta basada en contenido local QVAC." />{notice && <p className="notice" role="status">{notice}</p>}</section>;
}
