import Fastify, { type FastifyInstance } from "fastify";
import multipart from "@fastify/multipart";
import fastifyStatic from "@fastify/static";
import { randomUUID } from "node:crypto";
import { resolve } from "node:path";
import { config } from "./config.js";
import { LocalDatabase } from "./storage/database.js";
import { ProcedureSearch } from "./tools/search-procedure.js";
import { ingestPdf } from "./documents/pdf-ingestion.js";
import { QvacAdapter } from "./qvac/qvac-adapter.js";
import { AgentController } from "./agent/agent-controller.js";
import { ToolRegistry } from "./tools/tool-registry.js";
import { ensureSyntheticCases } from "./storage/synthetic-bootstrap.js";
import { z } from "zod";
import { ensureBankingData } from "./banking/banking-bootstrap.js";
import { answerClient, answerProcedure } from "./banking/local-assistant.js";
import { detectSyntheticRisks } from "./banking/risk-detector.js";
import { classifyDocument } from "./documents/classification.js";

type AppDependencies = { db: LocalDatabase; procedure: ProcedureSearch; adapter: QvacAdapter };
const errors = { INVALID_INPUT: "INVALID_INPUT", NOT_FOUND: "NOT_FOUND", UNSUPPORTED_DOCUMENT_FORMAT: "UNSUPPORTED_DOCUMENT_FORMAT", QVAC_NOT_READY: "QVAC_NOT_READY", AGENT_FORMAT_ERROR: "AGENT_FORMAT_ERROR", INTERNAL_ERROR: "INTERNAL_ERROR" } as const;
const escapeHtml = (value: unknown): string => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");

export async function buildApp(dependencies?: AppDependencies): Promise<{ app: FastifyInstance; dependencies: AppDependencies }> {
  const active = dependencies ?? { db: new LocalDatabase(), procedure: await ProcedureSearch.load(), adapter: new QvacAdapter() };
  if (!dependencies) await ensureSyntheticCases(active.db.db);
  await ensureBankingData(active.db.db);
  const app = Fastify({ logger: false, bodyLimit: config.MAX_DOCUMENT_SIZE_BYTES });
  const requestCache = new Map<string, unknown>();
  await app.register(multipart, { limits: { fileSize: config.MAX_DOCUMENT_SIZE_BYTES, files: 1 } });
  await app.register(fastifyStatic, { root: resolve("dist/ui"), prefix: "/" });
  app.get("/api/session", async () => ({ id: "local", synthetic: true }));
  app.get("/api/health", async () => ({ ok: true, host: config.HOST, port: config.PORT, provider: "QVAC local", model: config.QVAC_MODEL, ready: active.adapter.isReady() }));
  app.get<{ Querystring: { language?: string } }>("/api/client/products", async (request) => { const language = request.query.language === "en" ? "en" : "es"; return active.db.db.prepare("SELECT id, language, name, description, audience, requirements, version FROM product_catalog WHERE language = ? ORDER BY id").all(language); });
  app.get<{ Querystring: { language?: string; q?: string } }>("/api/client/guides", async (request) => { const language = request.query.language === "en" ? "en" : "es"; const query = request.query.q?.trim() ?? ""; return active.db.db.prepare("SELECT id, language, title, content, keywords, version FROM education_guides WHERE language = ? AND (lower(title) LIKE ? OR lower(content) LIKE ? OR lower(keywords) LIKE ?) ORDER BY id").all(language, `%${query.toLowerCase()}%`, `%${query.toLowerCase()}%`, `%${query.toLowerCase()}%`); });
  app.post<{ Body: { language?: string; query?: string } }>("/api/client/assistant", async (request, reply) => { const body = z.object({ language: z.enum(["es", "en"]).default("es"), query: z.string().trim().min(1).max(500) }).safeParse(request.body); if (!body.success) return reply.code(400).send({ code: errors.INVALID_INPUT, message: "Pregunta inválida" }); return answerClient(active.db.db, active.adapter, body.data.language, body.data.query); });
  app.post<{ Body: { productId?: string; language?: string; message?: string } }>("/api/client/orientation-requests", async (request, reply) => { const body = z.object({ productId: z.string().min(1), language: z.enum(["es", "en"]).default("es"), message: z.string().trim().min(1).max(1000) }).safeParse(request.body); if (!body.success || !active.db.db.prepare("SELECT 1 FROM product_catalog WHERE id = ? AND language = ?").get(body.success ? body.data.productId : "", body.success ? body.data.language : "")) return reply.code(400).send({ code: errors.INVALID_INPUT, message: "Solicitud de orientación inválida" }); const id = randomUUID(); active.db.db.prepare("INSERT INTO orientation_requests (id, product_id, language, message, status, created_at) VALUES (?, ?, ?, ?, 'pending_human_review', ?)").run(id, body.data.productId, body.data.language, body.data.message, new Date().toISOString()); return reply.code(201).send({ id, productId: body.data.productId, language: body.data.language, status: "pending_human_review" }); });
  app.get("/api/operations/orientation-requests", async () => active.db.db.prepare("SELECT id, product_id AS productId, language, message, status, created_at AS createdAt FROM orientation_requests ORDER BY created_at DESC").all());
  app.post<{ Body: { language?: string; query?: string } }>("/api/operations/procedure-assistant", async (request, reply) => { const body = z.object({ language: z.enum(["es", "en"]).default("es"), query: z.string().trim().min(1).max(500) }).safeParse(request.body); if (!body.success) return reply.code(400).send({ code: errors.INVALID_INPUT, message: "Consulta inválida" }); return answerProcedure(active.db.db, active.procedure, body.data.language, body.data.query); });
  app.get("/api/security/transactions", async () => active.db.db.prepare("SELECT id, customer_ref AS customerRef, occurred_at AS occurredAt, amount, currency, beneficiary, channel, country FROM transactions ORDER BY occurred_at, id").all());
  app.get("/api/security/alerts", async () => { detectSyntheticRisks(active.db.db); const rows = active.db.db.prepare("SELECT id, alert_type AS alertType, severity, message, transaction_ids AS transactionIds, evidence, status, created_at AS createdAt FROM risk_alerts ORDER BY created_at, id").all() as Array<{ id: string; alertType: string; severity: string; message: string; transactionIds: string; evidence: string; status: string; createdAt: string }>; return rows.map((row) => ({ ...row, transactionIds: JSON.parse(row.transactionIds), evidence: JSON.parse(row.evidence) })); });
  app.get("/api/cases", async () => active.db.db.prepare("SELECT id, status, created_at AS createdAt, updated_at AS updatedAt FROM cases ORDER BY created_at, id").all());
  app.get<{ Params: { caseId: string } }>("/api/cases/:caseId", async (request, reply) => { const row = active.db.db.prepare("SELECT id, status, created_at AS createdAt, updated_at AS updatedAt FROM cases WHERE id = ?").get(request.params.caseId); if (!row) return reply.code(404).send({ code: errors.NOT_FOUND, message: "Caso no encontrado" }); return row; });
  app.get<{ Params: { caseId: string } }>("/api/cases/:caseId/documents", async (request, reply) => {
    if (!active.db.db.prepare("SELECT 1 FROM cases WHERE id = ?").get(request.params.caseId)) return reply.code(404).send({ code: errors.NOT_FOUND, message: "Caso no encontrado" });
    return active.db.db.prepare("SELECT id, case_id AS caseId, filename, mime_type AS mimeType, page_count AS pageCount, sha256, created_at AS createdAt FROM documents WHERE case_id = ? ORDER BY created_at, id").all(request.params.caseId);
  });
  app.get<{ Params: { caseId: string } }>("/api/cases/:caseId/analysis", async (request, reply) => {
    if (!active.db.db.prepare("SELECT 1 FROM cases WHERE id = ?").get(request.params.caseId)) return reply.code(404).send({ code: errors.NOT_FOUND, message: "Caso no encontrado" });
    const fields = active.db.db.prepare("SELECT id, case_id AS caseId, document_id AS documentId, field_key AS fieldKey, value_text AS value, normalized_value AS normalizedValue, status, confidence, source_page AS sourcePage, source_quote AS sourceQuote, created_at AS createdAt FROM field_candidates WHERE case_id = ? ORDER BY created_at, id").all(request.params.caseId);
    const findings = active.db.db.prepare("SELECT id, case_id AS caseId, rule_id AS ruleId, severity, kind, message, document_id AS documentId, page, quote, created_at AS createdAt FROM findings WHERE case_id = ? ORDER BY created_at, id").all(request.params.caseId);
    return { fields, findings };
  });
  app.post<{ Params: { caseId: string } }>("/api/cases/:caseId/documents", async (request, reply) => {
    if (!active.db.db.prepare("SELECT 1 FROM cases WHERE id = ?").get(request.params.caseId)) return reply.code(404).send({ code: errors.NOT_FOUND, message: "Caso no encontrado" });
    const part = await request.file(); if (!part) return reply.code(400).send({ code: errors.INVALID_INPUT, message: "Falta el documento" });
    try { const parsed = await ingestPdf(await part.toBuffer(), { filename: part.filename, mimeType: part.mimetype }); const id = randomUUID(); const timestamp = new Date().toISOString(); const insert = active.db.db.transaction(() => { active.db.db.prepare("INSERT INTO documents (id, case_id, filename, mime_type, document_type, sha256, page_count, text_content, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)").run(id, request.params.caseId, parsed.filename, parsed.mimeType, classifyDocument(parsed.filename, parsed.text), parsed.sha256, parsed.pageCount, parsed.text, timestamp); const pageInsert = active.db.db.prepare("INSERT INTO document_pages (document_id, page, text_content) VALUES (?, ?, ?)"); for (const page of parsed.pages) pageInsert.run(id, page.page, page.text); active.db.db.prepare("UPDATE cases SET status = 'documentos_cargados', updated_at = ? WHERE id = ?").run(timestamp, request.params.caseId); }); insert(); return reply.code(201).send({ id, caseId: request.params.caseId, filename: parsed.filename, documentType: classifyDocument(parsed.filename, parsed.text), pageCount: parsed.pageCount, sha256: parsed.sha256 }); } catch (error) { return reply.code(400).send({ code: error && typeof error === "object" && "code" in error ? error.code : errors.UNSUPPORTED_DOCUMENT_FORMAT, message: error instanceof Error ? error.message : "Documento rechazado" }); }
  });
  app.get<{ Params: { id: string; page: string } }>("/api/documents/:id/pages/:page", async (request, reply) => { const row = active.db.db.prepare("SELECT id, case_id AS caseId, page_count AS pageCount FROM documents WHERE id = ?").get(request.params.id) as { id: string; caseId: string; pageCount: number | null } | undefined; const page = Number(request.params.page); const content = row ? active.db.db.prepare("SELECT text_content AS text FROM document_pages WHERE document_id = ? AND page = ?").get(request.params.id, page) as { text: string } | undefined : undefined; if (!row || !content || !Number.isInteger(page) || page < 1 || (row.pageCount !== null && page > row.pageCount)) return reply.code(404).send({ code: errors.NOT_FOUND, message: "Página no encontrada" }); return { documentId: row.id, caseId: row.caseId, page, text: content.text }; });
  app.post<{ Params: { caseId: string }; Body: { requestId?: string } }>("/api/cases/:caseId/agent-turn", async (request, reply) => { const requestId = request.body?.requestId; const cacheKey = requestId ? `${request.params.caseId}:${requestId}` : undefined; if (cacheKey && requestCache.has(cacheKey)) return requestCache.get(cacheKey); if (!active.adapter.isReady()) return reply.code(503).send({ code: errors.QVAC_NOT_READY, message: "QVAC local no está listo" }); const result = await new AgentController(active.db.db, active.adapter, new ToolRegistry()).run(request.params.caseId); if (cacheKey) requestCache.set(cacheKey, result); return result; });
  app.post<{ Params: { caseId: string }; Body: { fieldKey: string; value: string; message: string } }>("/api/cases/:caseId/answers", async (request, reply) => { try { const body = z.object({ fieldKey: z.string(), value: z.string().trim().min(1).max(500), message: z.string().trim().min(1).max(1000) }).parse(request.body); if (!active.db.db.prepare("SELECT 1 FROM cases WHERE id = ?").get(request.params.caseId)) return reply.code(404).send({ code: errors.NOT_FOUND, message: "Caso no encontrado" }); const id = randomUUID(); active.db.db.prepare("INSERT INTO user_answers (id, case_id, field_key, value_text, message, created_at) VALUES (?, ?, ?, ?, ?, ?)").run(id, request.params.caseId, body.fieldKey, body.value, body.message, new Date().toISOString()); return { id, caseId: request.params.caseId, ...body, status: "user_reported" }; } catch { return reply.code(400).send({ code: errors.INVALID_INPUT, message: "Respuesta inválida" }); } });
  app.post<{ Params: { caseId: string } }>("/api/cases/:caseId/report", async (request, reply) => { const row = active.db.db.prepare("SELECT id, status FROM cases WHERE id = ?").get(request.params.caseId) as { id: string; status: string } | undefined; if (!row) return reply.code(404).send({ code: errors.NOT_FOUND, message: "Caso no encontrado" }); const findings = active.db.db.prepare("SELECT rule_id AS ruleId, severity, kind, message, document_id AS documentId, page, quote FROM findings WHERE case_id = ? ORDER BY created_at, id").all(request.params.caseId) as Array<Record<string, unknown>>; const fields = active.db.db.prepare("SELECT field_key AS fieldKey, value_text AS value, status, source_page AS page, source_quote AS quote FROM field_candidates WHERE case_id = ? ORDER BY created_at, id").all(request.params.caseId) as Array<Record<string, unknown>>; const findingRows = findings.map((finding) => `<li><strong>${escapeHtml(finding.severity)}</strong> ${escapeHtml(finding.message)} — ${escapeHtml(finding.documentId ?? "sin documento")} ${escapeHtml(finding.page ? `p. ${finding.page}` : "")}<blockquote>${escapeHtml(finding.quote ?? "Sin cita: ausencia de campo")}</blockquote></li>`).join(""); const fieldRows = fields.map((field) => `<tr><td>${escapeHtml(field.fieldKey)}</td><td>${escapeHtml(field.value ?? "")}</td><td>${escapeHtml(field.status)}</td><td>${escapeHtml(field.quote ?? "")}</td></tr>`).join(""); const html = `<!doctype html><html lang="es"><meta charset="utf-8"><title>Reporte ${escapeHtml(row.id)}</title><style>body{font:14px system-ui;max-width:900px;margin:40px auto;color:#1d2925}blockquote{color:#65746a;border-left:3px solid #c9e85b;padding-left:12px}table{border-collapse:collapse;width:100%}td,th{border:1px solid #dfe6dd;padding:8px;text-align:left}</style><h1>DATOS SINTÉTICOS — DEMO</h1><p>Estado: <strong>${escapeHtml(row.status)}</strong></p><h2>Campos extraídos</h2><table><thead><tr><th>Campo</th><th>Valor</th><th>Estado</th><th>Evidencia</th></tr></thead><tbody>${fieldRows}</tbody></table><h2>Hallazgos</h2><ul>${findingRows || "<li>No hay hallazgos.</li>"}</ul><p>Reporte factual para revisión humana. Una discrepancia no prueba fraude.</p></html>`; return { caseId: row.id, html }; });
  app.setErrorHandler((_error, _request, reply) => reply.code(500).send({ code: errors.INTERNAL_ERROR, message: "Error interno" }));
  return { app, dependencies: active };
}
